"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 15:49:49.387113
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=300), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('revenue_musd', sa.Float(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('market', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('crunchbase_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('careers_url', sa.String(length=500), nullable=True),
    sa.Column('ats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_existing_client', sa.Boolean(), nullable=False),
    sa.Column('is_competitor', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('linkedin_validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('llm_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('progress', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icp_weight', sa.Float(), nullable=False),
    sa.Column('signal_weight', sa.Float(), nullable=False),
    sa.Column('hot_threshold', sa.Float(), nullable=False),
    sa.Column('warm_threshold', sa.Float(), nullable=False),
    sa.Column('weight_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recency_buckets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('undated_recency', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value_proposition', sa.Text(), nullable=False),
    sa.Column('event_weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('company_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('polarity', sa.String(length=10), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_events_company_id'), 'company_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_events_event_type'), 'company_events', ['event_type'], unique=False)
    op.create_table('disqualification_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disqualification_rules_service_id'), 'disqualification_rules', ['service_id'], unique=False)
    op.create_table('icp_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('markets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('industries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('countries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('employee_min', sa.Integer(), nullable=True),
    sa.Column('employee_max', sa.Integer(), nullable=True),
    sa.Column('revenue_min', sa.Float(), nullable=True),
    sa.Column('revenue_max', sa.Float(), nullable=True),
    sa.Column('min_fit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id')
    )
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('icp_score', sa.Float(), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('disqualified', sa.Boolean(), nullable=False),
    sa.Column('disqualification_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'service_id', name='uq_lead_scores_company_service')
    )
    op.create_index(op.f('ix_lead_scores_company_id'), 'lead_scores', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_final_score'), 'lead_scores', ['final_score'], unique=False)
    op.create_index(op.f('ix_lead_scores_service_id'), 'lead_scores', ['service_id'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'content_hash', name='uq_raw_documents_company_hash')
    )
    op.create_index(op.f('ix_raw_documents_company_id'), 'raw_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_source_type'), 'raw_documents', ['source_type'], unique=False)
    op.create_table('signal_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('weight', sa.String(length=10), nullable=False),
    sa.Column('source_hint', sa.String(length=10), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('is_negative', sa.Boolean(), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_questions_service_id'), 'signal_questions', ['service_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('answer', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('signal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['signal_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['disqualification_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_company_id'), 'signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_signals_service_id'), 'signals', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_service_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_company_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_signal_questions_service_id'), table_name='signal_questions')
    op.drop_table('signal_questions')
    op.drop_index(op.f('ix_raw_documents_source_type'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_company_id'), table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_lead_scores_service_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_final_score'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_company_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_table('icp_criteria')
    op.drop_index(op.f('ix_disqualification_rules_service_id'), table_name='disqualification_rules')
    op.drop_table('disqualification_rules')
    op.drop_index(op.f('ix_company_events_event_type'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_company_id'), table_name='company_events')
    op.drop_table('company_events')
    op.drop_table('services')
    op.drop_table('scoring_config')
    op.drop_table('pipeline_runs')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
