"""sources discovery and score movement

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 16:08:09.646285
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_state',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('cursor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('total_new_companies', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('companies', sa.Column('normalized_name', sa.String(length=300), nullable=False, server_default=sa.text("''")))
    op.add_column('companies', sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('companies', sa.Column('business_model', sa.String(length=10), nullable=False, server_default=sa.text("'unknown'")))
    op.add_column('companies', sa.Column('origin', sa.String(length=50), nullable=False, server_default=sa.text("'manual'")))
    op.add_column('companies', sa.Column('discovered_via', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('companies', sa.Column('registry_profiles', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('companies', sa.Column('tech_stack', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('companies', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    # Backfill the entity-resolution key for companies created before this migration.
    from sales_pipeline.sources.companies import normalize_company_name

    conn = op.get_bind()
    for cid, name in conn.execute(sa.text("SELECT id, name FROM companies")).fetchall():
        conn.execute(sa.text("UPDATE companies SET normalized_name = :n WHERE id = :i"), {"n": normalize_company_name(name), "i": cid})
    op.create_index(op.f('ix_companies_normalized_name'), 'companies', ['normalized_name'], unique=False)
    op.add_column('lead_scores', sa.Column('previous_score', sa.Float(), nullable=True))
    op.add_column('lead_scores', sa.Column('score_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scoring_config', sa.Column('discovery_countries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[\"RO\", \"MD\"]'")))
    op.add_column('pipeline_runs', sa.Column('kind', sa.String(length=20), nullable=False, server_default=sa.text("'enrichment'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'kind')
    op.drop_column('scoring_config', 'discovery_countries')
    op.drop_column('lead_scores', 'score_changed_at')
    op.drop_column('lead_scores', 'previous_score')
    op.drop_index(op.f('ix_companies_normalized_name'), table_name='companies')
    op.drop_column('companies', 'enriched_at')
    op.drop_column('companies', 'tech_stack')
    op.drop_column('companies', 'registry_profiles')
    op.drop_column('companies', 'discovered_via')
    op.drop_column('companies', 'origin')
    op.drop_column('companies', 'business_model')
    op.drop_column('companies', 'aliases')
    op.drop_column('companies', 'normalized_name')
    op.drop_table('source_state')
    # ### end Alembic commands ###
