"""Load stored data, run the scoring engine and upsert `lead_scores`."""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import or_, select
from sqlalchemy.orm import Session

from .models import Company, CompanyEvent, DisqualificationRule, LeadScore, ScoringConfig, Service, Signal, SignalQuestion
from .scoring import ScoreParams, score_lead


def get_scoring_config(db: Session) -> ScoringConfig:
    cfg = db.scalar(select(ScoringConfig).limit(1))
    if cfg is None:
        cfg = ScoringConfig()
        db.add(cfg)
        db.flush()
    return cfg


def latest_signals(db: Session, company_id: int, service_id: int | None = None) -> tuple[dict[int, Signal], dict[int, Signal]]:
    """Latest signal per question and per llm_question rule. Manual signals win over AI ones
    detected at the same time or earlier, because a rep validated them."""
    stmt = select(Signal).where(Signal.company_id == company_id).order_by(Signal.detected_at, Signal.id)
    by_q: dict[int, Signal] = {}
    by_rule: dict[int, Signal] = {}
    for s in db.scalars(stmt):
        if s.question_id is not None:
            prev = by_q.get(s.question_id)
            if prev is not None and prev.origin == "manual" and s.origin != "manual":
                continue
            by_q[s.question_id] = s
        elif s.rule_id is not None:
            by_rule[s.rule_id] = s
    return by_q, by_rule


def compute_lead(db: Session, company: Company, service: Service, params: ScoreParams | None = None, now: datetime | None = None):
    params = params or ScoreParams.from_model(get_scoring_config(db))
    questions = list(db.scalars(select(SignalQuestion).where(SignalQuestion.service_id == service.id)))
    rules = list(
        db.scalars(
            select(DisqualificationRule).where(
                or_(DisqualificationRule.service_id == service.id, DisqualificationRule.service_id.is_(None))
            )
        )
    )
    by_q, by_rule = latest_signals(db, company.id)
    events = list(db.scalars(select(CompanyEvent).where(CompanyEvent.company_id == company.id)))
    return score_lead(
        company=company,
        service=service,
        icp=service.icp,
        questions=questions,
        signals_by_question=by_q,
        rules=rules,
        rule_signals=by_rule,
        events=events,
        params=params,
        now=now,
    )


def recompute_scores(db: Session, company_ids: list[int] | None = None, service_ids: list[int] | None = None) -> list[LeadScore]:
    params = ScoreParams.from_model(get_scoring_config(db))
    cstmt = select(Company)
    if company_ids:
        cstmt = cstmt.where(Company.id.in_(company_ids))
    sstmt = select(Service).where(Service.active.is_(True))
    if service_ids:
        sstmt = sstmt.where(Service.id.in_(service_ids))
    services = list(db.scalars(sstmt))
    now = datetime.now(timezone.utc)
    out = []
    for company in db.scalars(cstmt):
        for service in services:
            res = compute_lead(db, company, service, params, now)
            row = db.scalar(select(LeadScore).where(LeadScore.company_id == company.id, LeadScore.service_id == service.id))
            if row is None:
                row = LeadScore(company_id=company.id, service_id=service.id)
                db.add(row)
            if row.final_score is not None and row.id is not None and abs((row.final_score or 0) - res.final_score) >= 0.5:
                row.previous_score = row.final_score
                row.score_changed_at = now
            previous_summary = (row.explanation or {}).get("summary", "")
            previous_top = (row.explanation or {}).get("top_signals", [])
            row.icp_score = res.icp_score
            row.signal_score = res.signal_score
            row.final_score = res.final_score
            row.tier = res.tier
            row.disqualified = res.disqualified
            row.disqualification_reasons = res.disqualification_reasons
            row.breakdown = res.breakdown
            row.explanation = {
                # The AI summary is only regenerated by a pipeline run or /explain; keep it
                # while the underlying top signals are unchanged.
                "summary": previous_summary if previous_top == res.top_signals else "",
                "top_signals": res.top_signals,
                "recommendation": res.recommendation,
                "freshest_signal_days": res.freshest_days,
            }
            row.computed_at = now
            out.append(row)
    db.commit()
    return out
